version: '3.1'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
      MYSQL_USER: forum
      MYSQL_PASSWORD: forum
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../Database/db.sql:/docker-entrypoint-initdb.d/db.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=mysql
    ports:
      - "9000:80"
    depends_on:
      - mysql
volumes:
  mysql_data:
