DROP DATABASE IF EXISTS forum;

CREATE DATABASE forum;
USE forum;

CREATE TABLE users (
    userID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nick VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(250) NOT NULL,
    creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE topics (
    topicID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    authorID INT NOT NULL,
    publicationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(50) NOT NULL UNIQUE,
    content VARCHAR(10000) NOT NULL,
    FOREIGN KEY (authorID) REFERENCES users(userID)
);

CREATE TABLE answers(
    answerID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    topicID INT NOT NULL,
    authorID INT NOT NULL,
    publicationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    content VARCHAR(10000) NOT NULL,
    FOREIGN KEY (topicID) REFERENCES topics(topicID),
    FOREIGN KEY (authorID) REFERENCES users(userID)
);
